name: OCM Build Test
# trigger manually
run-name: Build the OCM CLI
on:
  push:
  workflow_dispatch:
    inputs:
      use-release:
        type: boolean
        description: use latest pre-built release instead of building from HEAD
        default: false
# env:
jobs:
  test-ocm:
    runs-on: ubuntu-latest
    steps:
    - name: setup OCM
      if: ${{ inputs.use-release }}
      uses: open-component-model/ocm-setup-action@main
    - name: checkout
      uses: actions/checkout@v3
      if: ${{ ! inputs.use-release }}
      with:
        repository: open-component-model/ocm
        path: ocm
    - name: Set up Go
      if: ${{ ! inputs.use-release }}
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.2
    - name: build
      if: ${{ ! inputs.use-release }}
      run: |
        cd ocm
        make install
    - name: test-ocm
      run: ocm --version
