name: test-cred
# trigger manually
run-name: Test ocm CLI with credentials
on:
  workflow_dispatch:
# env:
jobs:
  test-ocm:
    runs-on: ubuntu-latest
    steps:
    - name: create credentials
      run: |
        mkdir auth
        htpasswd -Bbn ocmuser abc123 > auth/htpasswd
        htpasswd -b -v auth/htpasswd ocmuser abc123
