name: OCM Integration Tests
# trigger manually
run-name: OCM CLI Integration Tests
on:
  workflow_dispatch: ~
  schedule:
    - cron: '0 2 * * *'  # every day at 2AM
# env:
jobs:
  test-ocm:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup OCM
      uses: open-component-model/ocm-setup-action@main
    - name: create-cert
      run: |
        FDQN_NAME=`hostname --fqdn`
        HNAME=`hostname`
        echo "working dir is: $PWD"
        echo "home-dir: $HOME"
        echo "fqdn hostame is: $FDQN_NAME"
        sudo rm -rf certs
        mkdir -p certs
        openssl req -newkey rsa:4096 -nodes -sha256 -keyout certs/ociregistry.key -addext "subjectAltName = DNS:${FDQN_NAME}" -x509 -days 365 -out certs/ociregistry.crt -subj "/C=DE/ST=Baden-Wuertemberg/L=Walldorf/O=SAP/OU=ocm/CN=${HNAME}"
        openssl x509 -noout -text -in certs/ociregistry.crt
        sudo cp certs/ociregistry.crt /usr/local/share/ca-certificates
        sudo update-ca-certificates
        echo "FDQN_NAME=${FDQN_NAME}" >> $GITHUB_ENV
    - name: create user and credentials
      run: |
        mkdir -p auth
        # generate a random password
        PASSWD=`head /dev/urandom | tr -dc 'A-Za-z0-9!#-$%&=+-' | head -c12`
        USER_NAME=ocmuser
        htpasswd -Bbn ocmuser ${PASSWD} > auth/htpasswd
        htpasswd -b -v auth/htpasswd ${USER_NAME} ${PASSWD}
        echo "PASSWD=${PASSWD}" >> $GITHUB_ENV
        echo "USER_NAME=${USER_NAME}" >> $GITHUB_ENV
    - name: start OCI registry (docker)
      run: |
        docker run -d -p 443:443  --name registry \
          -v ${{ github.workspace}}/certs:/certs \
          -v ${{ github.workspace}}/auth:/auth \
          -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
          -e REGISTRY_AUTH=htpasswd \
          -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
          -e REGISTRY_HTTP_ADDR=:443 \
          -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/ociregistry.crt \
          -e REGISTRY_HTTP_TLS_KEY=/certs/ociregistry.key \
          registry:2.8.1
    - name: Wait for OCI registry to become ready
      timeout-minutes: 1
      run: |
        while ! curl https://${{ env.FDQN_NAME }}/v2
        do
          echo "Waiting for container to become ready... still trying"
          sleep 1
        done
        echo "$Registy container is ready"
    - name: Pyhon add CA
      run: |
        location=`python3 -c "import certifi; print(certifi.where());"`
        cat ${{ github.workspace}}/certs/ociregistry.crt >> location
        python -c "import urllib.request; urllib.request.urlopen('https://${{ env.FDQN_NAME }}')"
    - name: Install Pythpn Libs
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest ./tests
    - name: stop docker registry
      if: always()
      run: |
        docker container stop registry
        docker container rm -v registry
