name: OCM Slack Message
# trigger manually
run-name: OCM Send Slack Message
on:
  workflow_dispatch: ~
# env:
jobs:
  test-ocm:
    runs-on: ubuntu-latest
    steps:
    - name: checkout inttest
      uses: actions/checkout@v3
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
        channel-id: 'C057KU48M7Y'
        # For posting a simple plain text message
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "OCM Integration Test Report",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Integration Test:*\nOCM CLI"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Status:*\n${{ job.status == 'success' && ':fiori-success:' || ':fiori-error:' }}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Commit:*\n${{ github.event.head_commit.url }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Action:*\n<https://github.com/jensh007/testocm/actions/workflows/slack.yaml|Github Action>"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://jensh007.github.io/testocm/report.html|TestReport>"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}