name: test-ocm
# trigger manually
run-name: Test ocm CLI
on:
  workflow_dispatch:
# env:
#   VERSION: "1.0.0"
#   COMP_NAME: acme.org/demo/simpleserver
#   PROVIDER: github.com/acme
#   REPO_URL: ghcr.io/open-component-model/ocm
jobs:
  test-ocm:
    runs-on: ubuntu-latest
    services:
      ociregistry:
        image: registry:2.8.1
        env:
          SOME_VAR: my_value
        ports:
          - 5000:5000
        volumes:
          - /data:/data
        options: --cpus 1 --name registry
    steps:
    - name: setup OCM
      uses: open-component-model/ocm-setup-action@main
    - name: Run OCM
      run: ocm --version
    - name: Test OCM
      run: ocm transfer artifacts gcr.io/google-containers/pause:3.2 127.0.0.1:5000/images/pause:3.2
