name: test-ocm
# trigger manually
run-name: Test ocm CLI
on:
  workflow_dispatch:
# env:
#   VERSION: "1.0.0"
#   COMP_NAME: acme.org/demo/simpleserver
#   PROVIDER: github.com/acme
#   REPO_URL: ghcr.io/open-component-model/ocm
jobs:
  test-ocm:
    runs-on: ubuntu-latest
    services:
      ociregistry:
        image: registry:2.8.1
        env:
          REGISTRY_HTTP_ADDR: :5000
          # REGISTRY_HTTP_TLS_CERTIFICATE: /certs/ociregistry.crt
          # REGISTRY_HTTP_TLS_KEY: /certs/ociregistry.key
        ports:
          - 5000:5000
        volumes:
          - ${{ github.workspace}}/certs:/certs
        #   - /data:/data
        options: --cpus 1 --name registry
    steps:
    - name: setup OCM
      uses: open-component-model/ocm-setup-action@main
    - name: Run OCM
      run: ocm --version
    - name: create-cert
      run: |
        HNAME=`hostname --fqdn`
        echo "pwd is: $PWD"
        echo "fwdn hostame is: $HNAME"
        sudo rm -rf certs
        mkdir -p certs
        openssl req -newkey rsa:4096 -nodes -sha256 -keyout certs/ociregistry.key -addext "subjectAltName = DNS:${HNAME}" -x509 -days 365 -out certs/ociregistry.crt -subj "/C=DE/ST=Baden-Wuertemberg/L=Walldorf/O=SAP/OU=ocm/CN=${HNAME}"
        openssl x509 -noout -text -in certs/ociregistry.crt
        sudo cp certs/ociregistry.crt /usr/local/share/ca-certificates
        sudo update-ca-certificates
    - name: Test Curl
      run: |
        HNAME=`hostname --fqdn`
        curl -v  http://${HNAME}:5000/v2
    # - name: Test OCM
    #   run: |
    #     HNAME=`hostname --fqdn`
    #     ocm transfer artifacts gcr.io/google-containers/pause:3.2 ${HNAME}:5000/images/pause:3.2
