name: test-ocm
# trigger manually
run-name: Test ocm CLI
on:
  workflow_dispatch:
# env:
#   VERSION: "1.0.0"
#   COMP_NAME: acme.org/demo/simpleserver
#   PROVIDER: github.com/acme
#   REPO_URL: ghcr.io/open-component-model/ocm
jobs:
  test-ocm:
    runs-on: ubuntu-latest
    steps:
    - name: setup OCM
      uses: open-component-model/ocm-setup-action@main
    - name: Run OCM
      run: ocm --version
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: registry:2.8.1
      env:
        NODE_ENV: development
      ports:
        - 5000
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1 --name registry
    steps:
      - name: Check for dockerenv file
        run: docker image list